# Generated by Django 5.0.14 on 2025-12-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite_color",
            field=models.CharField(default="red", max_length=100),
            preserve_default=False,
        ),
    ]
