# Generated by Django 5.0.14 on 2025-12-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_favorite_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="favorite_color",
        ),
    ]
